### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by EverybodyKurts** [EverybodyKurts/Feliz.Plotly#3]
- [ ] Figure out how to publish to npm
- [ ] Create a github codespace to allow new developers to contribute to project
- [ ] Automate publishing docs and new releases
